import 'package:flutter/material.dart';

class TelaCliente extends StatefulWidget {
  const TelaCliente({Key? key}) : super(key: key);

  @override
  _TelaClienteState createState() => _TelaClienteState();
}

class _TelaClienteState extends State<TelaCliente> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Cliente"),
        backgroundColor: Colors.lime,
      ),
      body: Container(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(child:
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [Row(
            children: [
              Image.asset("imagens/detalhe_cliente.png"),
              Padding(padding: EdgeInsets.only(left: 10)),
              Text("Cliente", style:
              TextStyle(color: Colors.lime, fontSize: 16),)
            ],
          ),

            Padding(padding: EdgeInsets.only(top: 32),
            ),
            Text("ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS")
          ],
        )
        ),
      ),
    );
  }
}
