import 'package:flutter/material.dart';

class TelaContato extends StatefulWidget {
  const TelaContato({Key? key}) : super(key: key);

  @override
  _TelaContatoState createState() => _TelaContatoState();
}

class _TelaContatoState extends State<TelaContato> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Contato"),
        backgroundColor: Colors.lightGreen,
      ),
      body: Container(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(child:
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [Row(
            children: [
              Image.asset("imagens/detalhe_contato.png"),
              Padding(padding: EdgeInsets.only(left: 10)),
              Text("Contato", style:
              TextStyle(color: Colors.lightGreen, fontSize: 16),)
            ],
          ),

            Padding(padding: EdgeInsets.only(top: 32),
            ),
            Text("ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS")
          ],
        )
        ),
      ),
    );
  }
}
