import 'package:flutter/material.dart';

class TelaServico extends StatefulWidget {
  const TelaServico({Key? key}) : super(key: key);

  @override
  _TelaServicoState createState() => _TelaServicoState();
}

class _TelaServicoState extends State<TelaServico> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Serviço"),
        backgroundColor: Colors.cyan,
      ),
      body: Container(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(child:
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [Row(
            children: [
              Image.asset("imagens/detalhe_servico.png"),
              Padding(padding: EdgeInsets.only(left: 10)),
              Text("Serviço", style:
              TextStyle(color: Colors.cyan, fontSize: 16),)
            ],
          ),

            Padding(padding: EdgeInsets.only(top: 32),
            ),
            Text("ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS")
          ],
        )
        ),
      ),
    );
  }
}
