import 'package:flutter/material.dart';

class TelaEmpresa extends StatefulWidget {
  const TelaEmpresa({Key? key}) : super(key: key);

  @override
  _TelaEmpresaState createState() => _TelaEmpresaState();
}

class _TelaEmpresaState extends State<TelaEmpresa> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Empresa"),
        backgroundColor: Colors.green,
      ),
      body: Container(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(child:
        Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [Row(
            children: [
              Image.asset("imagens/detalhe_empresa.png"),
              Padding(padding: EdgeInsets.only(left: 10)),
              Text("Sobre a empresa", style:
              TextStyle(color: Colors.red, fontSize: 16),)
            ],
          ),

            Padding(padding: EdgeInsets.only(top: 32),
            ),
            Text("ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS"
                "ASIJSAIJASJASIJASIJASIJIASASIJSAIJASJASIJASIJASIJIAS")
          ],
        )
        ),
      ),
    );
  }
}
